theme: minima
title: Just got a Samsung Galaxy Flex Alpha
author: Gr3yta5ks
email: byfcx@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  # Write an awesome description for your new site here. You can edit this
  # line in _config.yml. It will appear in your document head meta (for
  # Google search results) and in your feed.xml site description.
  Things I am looking forward to Install and Setup on this new laptop
  Ultimately wanting to better my skills using Git, Github, Git-Towers, GitKraken, Gitpod, VScode, Windows Terminal

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username: your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
